#!/usr/bin/env bash
# One-command Expo + mobile setup for myfr.ai
# Usage: ./scripts/mobile-expo-setup.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MOBILE="$ROOT/mobile"
ENV_LOCAL="$ROOT/.env.local"
MOBILE_ENV="$MOBILE/.env"
PROJECT_ID="ec89741c-6973-4ab8-9047-6934e9e9f072"
PRODUCTION_API="https://myfr.ai"

green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
red() { printf '\033[31m%s\033[0m\n' "$*"; }

mask_secret() {
  local s="$1"
  if [ -z "$s" ]; then echo "(missing)"; return; fi
  printf '%s...%s' "$(printf '%.8s' "$s")" "$(echo "$s" | sed 's/.*\(....\)$/\1/')"
}

read_env_local() {
  SUPABASE_URL=""
  SUPABASE_ANON=""
  if [ ! -f "$ENV_LOCAL" ]; then
    red "Missing $ENV_LOCAL — run: npm run setup"
    exit 1
  fi
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      NEXT_PUBLIC_SUPABASE_URL=*) SUPABASE_URL="${line#NEXT_PUBLIC_SUPABASE_URL=}" ;;
      NEXT_PUBLIC_SUPABASE_ANON_KEY=*) SUPABASE_ANON="${line#NEXT_PUBLIC_SUPABASE_ANON_KEY=}" ;;
    esac
  done < "$ENV_LOCAL"
  if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON" ] || echo "$SUPABASE_ANON" | grep -qiE 'your-anon-key|PASTE'; then
    red "Invalid Supabase keys in .env.local — run: npm run setup"
    exit 1
  fi
}

detect_lan_ip() {
  local ip=""
  for iface in en0 en1 en2 bridge0; do
    ip="$(ipconfig getifaddr "$iface" 2>/dev/null || true)"
    [ -n "$ip" ] && break
  done
  if [ -z "$ip" ]; then
    ip="$(ifconfig 2>/dev/null | awk '/inet / && $2 != "127.0.0.1" { print $2; exit }' || true)"
  fi
  echo "$ip"
}

verify_expo_config() {
  if [ ! -f "$MOBILE/eas.json" ]; then
    red "Missing mobile/eas.json"
    exit 1
  fi
  if ! grep -q "$PROJECT_ID" "$MOBILE/app.json"; then
    red "mobile/app.json projectId mismatch (expected $PROJECT_ID)"
    exit 1
  fi
  green "✓ Expo project linked ($PROJECT_ID)"
  green "✓ eas.json present"
}

write_mobile_env() {
  local lan_ip api_url
  lan_ip="$(detect_lan_ip)"
  if [ -n "$lan_ip" ]; then
    api_url="http://${lan_ip}:3000"
  else
    api_url="http://localhost:3000"
    yellow "Could not detect LAN IP — phone testing may need manual EXPO_PUBLIC_API_URL in mobile/.env"
  fi

  cat > "$MOBILE_ENV" <<EOF
# Generated by scripts/mobile-expo-setup.sh — do not commit
EXPO_PUBLIC_API_URL=${api_url}
EXPO_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON}
EOF
  green "✓ Wrote mobile/.env (API → ${api_url}, Supabase anon $(mask_secret "$SUPABASE_ANON"))"
}

install_deps() {
  green "Installing mobile dependencies..."
  (cd "$MOBILE" && npm install --no-audit --no-fund)
}

sync_eas_env() {
  if ! (cd "$MOBILE" && npx eas-cli whoami >/dev/null 2>&1); then
    yellow "EAS not logged in — skipping cloud env sync"
    yellow "Run once: cd mobile && npx eas-cli login"
    return 0
  fi

  green "Syncing EAS environment variables (production, preview, development)..."
  local env name value vis
  for env in production preview development; do
    for pair in \
      "EXPO_PUBLIC_SUPABASE_URL|${SUPABASE_URL}|plaintext" \
      "EXPO_PUBLIC_SUPABASE_ANON_KEY|${SUPABASE_ANON}|sensitive" \
      "EXPO_PUBLIC_API_URL|${PRODUCTION_API}|plaintext"; do
      IFS='|' read -r name value vis <<< "$pair"
      if (cd "$MOBILE" && npx eas-cli env:create "$env" \
        --name "$name" --value "$value" --visibility "$vis" \
        --force --non-interactive >/dev/null 2>&1); then
        if [[ "$name" == *ANON_KEY* ]]; then
          green "  ✓ $env $name $(mask_secret "$value")"
        else
          green "  ✓ $env $name $value"
        fi
      else
        yellow "  ~ $env $name (unchanged or update skipped)"
      fi
    done
  done
}

print_done() {
  local lan_ip
  lan_ip="$(detect_lan_ip)"
  echo ""
  green "=== Mobile setup complete ==="
  echo ""
  echo "Open the app on your phone (2 terminals):"
  echo ""
  echo "  Terminal 1 — web API:"
  echo "    cd $ROOT && ./scripts/dev.sh"
  echo ""
  echo "  Terminal 2 — Expo (QR code):"
  echo "    cd $MOBILE && npx expo start"
  echo ""
  echo "On iPhone: install Expo Go, scan the QR code, same Wi‑Fi as this Mac."
  if [ -n "$lan_ip" ]; then
    echo "Phone API URL: http://${lan_ip}:3000"
  fi
  echo ""
  echo "Simulator shortcut (Mac + Xcode): cd mobile && npm run ios"
  echo ""
  yellow "One-time expo.dev click (GitHub cloud builds):"
  echo "  https://expo.dev/accounts/edmond808/projects/myfrai/github"
  echo "  → Base directory: mobile"
  echo "  → Production branch: main"
  echo ""
}

main() {
  echo "myfr.ai — mobile / Expo setup"
  echo ""
  read_env_local
  verify_expo_config
  write_mobile_env
  install_deps
  sync_eas_env
  print_done
}

main "$@"
